# <div style="background:rgba(226, 72, 25, 0.64); padding:18px; border-radius:12px; font-size:0.9em; margin-bottom:16px; color:#fff; font-weight:bold; width: max-content;"> NumPy Basics - Arrays and Vectorized Computation
</div>

**Basado en el libro "Python for Data Analysis, 3rd Edition" de Wes McKinney**

## <div style="color:#4DA6FF;">Introducción: ¿Por qué NumPy es fundamental?</div>

NumPy (abreviatura de Numerical Python) es mucho más que una librería de computación numérica: Es la <span style="color:#FFD633; font-weight:bold;">piedra angular</span> del ecosistema científico de Python. Su importancia radica en que proporciona la base computacional sobre la cual se construyen prácticamente todas las librerías de análisis de datos, machine learning y computación científica.

---

## <div style="color:#4DA6FF;">El ecosistema NumPy: La base de todo</div>

NumPy actúa como el lenguaje común en el intercambio de datos en Python.  

##### <div style="background:rgba(167, 156, 140, 0.69); padding:12px; border-radius:8px; font-size:0.9em; color:#fff; width: max-content;"> Cuando usas <b>pandas</b>, <b>scikit-learn</b>, <b>matplotlib</b> o <b>scipy</b>, todos trabajan internamente con arrays de NumPy.
</div>

Esta interoperabilidad significa que:

- <span style="color:#FFD633; font-weight:bold;">pandas</span> convierte DataFrames a arrays NumPy  
- <span style="color:#FFD633; font-weight:bold;">scikit-learn</span> espera arrays como entrada  
- <span style="color:#FFD633; font-weight:bold;">matplotlib</span> renderiza gráficos desde arrays  
- <span style="color:#FFD633; font-weight:bold;">scipy</span> procesa arrays para cálculos científicos  

---

## <div style="color:#4DA6FF;">¿Por qué NumPy es tan eficiente?</div>

1. <span style="color:#FFD633; font-weight:bold;">Memoria contigua</span>: bloques contiguos de memoria, acceso rápido y cache-friendly.  
2. <span style="color:#FFD633; font-weight:bold;">Algoritmos C optimizados</span>: se ejecutan en C compilado.  
3. <span style="color:#FFD633; font-weight:bold;">Vectorización</span>: operaciones aplicadas a arrays completos.  
4. <span style="color:#FFD633; font-weight:bold;">Tipos de datos optimizados</span>: control de precisión y memoria.  

---

## <div style="color:#4DA6FF;">Comparación de rendimiento: NumPy vs Python puro</div>

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]


2.8 ms ± 124 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
48.9 ms ± 879 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### <div style="color:#4DA6FF;">NumPy en el contexto del análisis de datos moderno</div> 

En el análisis de datos contemporáneo, NumPy proporciona:

 
- <span style="color:#FFD633; font-weight:bold;">Operaciones vectorizadas</span> para limpieza y transformación de datos masivos
- <span style="color:#FFD633; font-weight:bold;">Algoritmos de agregación</span> optimizados para estadísticas descriptivas
- <span style="color:#FFD633; font-weight:bold;">Operaciones de álgebra lineal</span> para análisis multivariado
- <span style="color:#FFD633; font-weight:bold;">Generación de datos aleatorios</span> para simulaciones y validación cruzada
- <span style="color:#FFD633; font-weight:bold;">Interfaz unificada</span> para integración con código C/C++/Fortran legacy

## <div style="color:#4DA6FF;">*4.1 El NumPy ndarray: Un Objeto de Array Multidimensional*</div> 


El **`ndarray`** es el objeto central de NumPy: un contenedor rápido y flexible para grandes conjuntos de datos que permite realizar operaciones matemáticas en bloques completos usando sintaxis similar a operaciones entre elementos escalares.

### <div style="color:#4DA6FF;">**Creación de ndarrays**</div>

##### <div>Método básico: `np.array()`</div>

In [3]:
# Array 1D a partir de una lista
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print("Array 1D:")
print(arr1)

# Array 2D a partir de lista de listas
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print("Array 2D:")
print(arr2)


Array 1D:
[6.  7.5 8.  0.  1. ]
Array 2D:
[[1 2 3 4]
 [5 6 7 8]]


### <div style="color:#4DA6FF;">**Funciones de creación especializadas**</div>


In [4]:
# Arrays de ceros y unos
print("Array de ceros:", np.zeros(10))
print("Array de unos 3x6:")
print(np.ones((3, 6)))
print("\n") 
# Array vacío (más rápido, pero con valores "basura")
print("Array vacío 2x3x2:")
print("empty utiliza memoria sin inicializar, lo que puede contener basura")
print(np.empty((2, 3, 2)))

# Secuencias
print("\n") 
print("Secuencia 0-14:", np.arange(15))
print("\n") 
print("Secuencia con paso:", np.arange(0, 20, 2))
print("\n") 
print("Secuencia de 5 elementos entre 0 y 1:", np.linspace(0, 1, 5))

Array de ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array de unos 3x6:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Array vacío 2x3x2:
empty utiliza memoria sin inicializar, lo que puede contener basura
[[[4.45057637e-308 1.78021527e-306]
  [8.45549797e-307 1.37962049e-306]
  [1.11260619e-306 1.78010255e-306]]

 [[9.79054228e-307 4.45057637e-308]
  [8.45596650e-307 9.34602321e-307]
  [4.94065646e-322 6.89327393e-042]]]


Secuencia 0-14: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Secuencia con paso: [ 0  2  4  6  8 10 12 14 16 18]


Secuencia de 5 elementos entre 0 y 1: [0.   0.25 0.5  0.75 1.  ]


### <div style="color:#4DA6FF;">**Tipos de datos para ndarrays**</div>

El **`dtype`** es un objeto especial que contiene la información que el **`ndarray`** necesita para interpretar un bloque de memoria como un tipo particular de dato.

<span style="color:#FFD633; font-weight:bold;">**BUENA PRÁCTICA**</span>: Ser explícito con los tipos de datos es fundamental para optimizar memoria.

In [5]:
# Crear arrays con tipos específicos
arr_int32 = np.array([1, 2, 3, 4], dtype=np.int32)
arr_float64 = np.array([1, 2, 3, 4], dtype=np.float64)

print(f"int32: {arr_int32.dtype}, tamaño: {arr_int32.nbytes} bytes")
print(f"float64: {arr_float64.dtype}, tamaño: {arr_float64.nbytes} bytes")


int32: int32, tamaño: 16 bytes
float64: float64, tamaño: 32 bytes


### <div style="color:#4DA6FF;">**Tipos de datos comunes:**</div>

- **`np.int32`**, **`np.int64`**  &rarr; enteros de 32 y 64 bits

- **`np.float32`**, **`np.float64`** &rarr; flotantes de 32 y 64 bits

- **`np.bool_`** &rarr; booleanos

- **`np.string_`**, **`np.unicode_`** &rarr; strings

###### **Leer el capitulo 4 para conocer todos los tipos disponibles**

## <div style="color:#4DA6FF;">*4.2 Vectorización y Broadcasting: El Corazón de NumPy*</div>

### <div style="color:#4DA6FF;">**Vectorización: La Revolución del Rendimiento**</div> 

La vectorización es la característica más transformadora de NumPy. Permite realizar operaciones matemáticas en arrays completos sin necesidad de bucles explícitos, transformando código que antes requería segundos en código que se ejecuta en milisegundos.

#### <div style="color:#4DA6FF;">**¿Qué es la vectorización?**</div>  

La vectorización significa que las operaciones se aplican automáticamente a todos los elementos de un array simultáneamente, aprovechando:

- **Instrucciones SIMD** (Single Instruction, Multiple Data) del procesador

- **Optimizaciones de compilador** en el código C subyacente

- **Acceso secuencial a memoria** que maximiza el uso de la caché

- **Paralelización implícita** en operaciones vectoriales

#### <div style="color:#4DA6FF; text-align:center;">**Operaciones elemento a elemento**</div>  

In [32]:
# Arrays de ejemplo
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print("Suma:", arr1 + arr2)           # [ 6  8 10 12]
print("Resta:", arr1 - arr2)          # [-4 -4 -4 -4]
print("Multiplicación:", arr1 * arr2) # [ 5 12 21 32]
print("División:", arr1 / arr2)       # [0.2 0.333... 0.429... 0.5]
print("Potencia:", arr1 ** 2)         # [ 1  4  9 16]

# Operaciones más complejas
print("Raíz cuadrada:", np.sqrt(arr1))
print("Exponencial:", np.exp(arr1))
print("Seno:", np.sin(arr1))

Suma: [ 6  8 10 12]
Resta: [-4 -4 -4 -4]
Multiplicación: [ 5 12 21 32]
División: [0.2        0.33333333 0.42857143 0.5       ]
Potencia: [ 1  4  9 16]
Raíz cuadrada: [1.         1.41421356 1.73205081 2.        ]
Exponencial: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Seno: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


#### <div style="color:#4DA6FF; text-align:center;">**Operaciones con escalares**</div>  

In [7]:

arr = np.array([1, 2, 3, 4, 5])

print("Array original:", arr)
print("Multiplicado por 2:", arr * 2)
print("Elevado al cuadrado:", arr ** 2)
print("Raíz cuadrada:", np.sqrt(arr))
print("Exponencial:", np.exp(arr))

# Ejemplo práctico: normalización
normalized = (arr - np.mean(arr)) / np.std(arr)
print("Normalizado:", normalized)

Array original: [1 2 3 4 5]
Multiplicado por 2: [ 2  4  6  8 10]
Elevado al cuadrado: [ 1  4  9 16 25]
Raíz cuadrada: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Normalizado: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


<span style="color:#FFD633; font-weight:bold;">**NOTA:**</span> NumPy aplica automáticamente operaciones con escalares a todos los elementos del array.

#### <div style="color:#4DA6FF; text-align:center;">**Comparaciones y operaciones lógicas vectorizadas**</div>


In [8]:
arr = np.array([1, 2, 3, 4, 5])

# Comparaciones vectorizadas
print("Mayor que 3:", arr > 3)        # [False False False  True  True]
print("Igual a 3:", arr == 3)         # [False False  True False False]

# Operaciones lógicas vectorizadas
print("Entre 2 y 4:", (arr >= 2) & (arr <= 4))  # [False  True  True  True False]
print("Menor que 2 o mayor que 4:", (arr < 2) | (arr > 4))  # [ True False False False  True]

Mayor que 3: [False False False  True  True]
Igual a 3: [False False  True False False]
Entre 2 y 4: [False  True  True  True False]
Menor que 2 o mayor que 4: [ True False False False  True]


#### <div style="color:#4DA6FF;">**Broadcasting: Operaciones entre Arrays de Diferentes Formas**</div>

El broadcasting es un conjunto de reglas que permite a NumPy realizar operaciones entre arrays de diferentes formas. Es una característica fundamental que hace que NumPy sea tan expresivo y eficiente.

##### <div style="color:#4DA6FF;">Reglas del broadcasting</div>

- **Regla 1** &rarr; Si los arrays tienen diferentes números de dimensiones, se añaden dimensiones de tamaño 1 al array con menos dimensiones.

- **Regla 2** &rarr; Si los arrays tienen la misma dimensión pero diferentes tamaños, y uno de ellos tiene tamaño 1, se estira para coincidir con el otro.

- **Regla 3** &rarr; Si los arrays tienen diferentes tamaños en cualquier dimensión y ninguno tiene tamaño 1, se produce un error.

#### <div style="color:#4DA6FF; text-align:center;">**Ejemplos de broadcasting**</div>

In [9]:
# Ejemplo 1: Array 1D + escalar
arr = np.array([1, 2, 3, 4])
result = arr + 5
print("Array + escalar:")
print(f"{arr} + 5 = {result}")

# Ejemplo 2: Array 2D + Array 1D
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

print("\nArray 2D:")
print(arr_2d)
print("Array 1D:", arr_1d)

result = arr_2d + arr_1d
print("\n")
print("Resultado del broadcasting:")
print(result)
# [[11 22 33]
#  [14 25 36]]

Array + escalar:
[1 2 3 4] + 5 = [6 7 8 9]

Array 2D:
[[1 2 3]
 [4 5 6]]
Array 1D: [10 20 30]


Resultado del broadcasting:
[[11 22 33]
 [14 25 36]]


<span style="color:#FFD633; font-weight:bold;">**BUENA PRÁCTICA:**</span> El broadcasting es excelente para operaciones como normalización, donde necesitas aplicar la misma operación a múltiples filas o columnas.

In [10]:
# Datos de ejemplo (3 muestras, 4 características)
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print("Datos originales:")
print(data)

# Calcular media y desviación estándar por característica
mean_features = np.mean(data, axis=0)
std_features = np.std(data, axis=0)

print(f"\nMedia por característica: {mean_features}")
print(f"Desviación estándar por característica: {std_features}")

# Normalización usando broadcasting
normalized_data = (data - mean_features) / std_features
print("\nDatos normalizados:")
print(normalized_data)

Datos originales:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Media por característica: [5. 6. 7. 8.]
Desviación estándar por característica: [3.26598632 3.26598632 3.26598632 3.26598632]

Datos normalizados:
[[-1.22474487 -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487  1.22474487]]


## <div style="color:#4DA6FF;">*4.3 Funciones Universales (ufuncs) y Operaciones de Agregación*</div>

### <div style="color:#4DA6FF;">**Funciones Universales: La Base de la Eficiencia**</div>

Las funciones universales son funciones que operan elemento a elemento en arrays de NumPy. Son la base de la eficiencia de NumPy y proporcionan una interfaz consistente para operaciones matemáticas.

#### <div style="color:#4DA6FF; text-align:center;">**Funciones matemáticas básicas**</div>

In [33]:
arr = np.array([0, 1, 2, 3, 4])

print("Array original:", arr)
print("Exponencial:", np.exp(arr))
print("Logaritmo natural:", np.log(arr + 1))  # +1 para evitar log(0)
print("Seno:", np.sin(arr))
print("Coseno:", np.cos(arr))
print("Raíz cuadrada:", np.sqrt(arr))
print("Valor absoluto:", np.abs(arr))

# Funciones trigonométricas
angles = np.array([0, np.pi/4, np.pi/2, np.pi])
print("Ángulos (radianes):", angles)
print("Seno:", np.sin(angles))
print("Coseno:", np.cos(angles))
print("Tangente:", np.tan(angles))

Array original: [0 1 2 3 4]
Exponencial: [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
Logaritmo natural: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Seno: [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
Coseno: [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
Raíz cuadrada: [0.         1.         1.41421356 1.73205081 2.        ]
Valor absoluto: [0 1 2 3 4]
Ángulos (radianes): [0.         0.78539816 1.57079633 3.14159265]
Seno: [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
Coseno: [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]
Tangente: [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.22464680e-16]


#### <div style="color:#4DA6FF; text-align:center;">**Funciones de agregación optimizadas**</div> 

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array 2D:")
print(arr)

print(f"\nSuma total: {np.sum(arr)}")
print(f"Media total: {np.mean(arr):.2f}")
print(f"Desviación estándar total: {np.std(arr):.2f}")
print(f"Mínimo: {np.min(arr)}")
print(f"Máximo: {np.max(arr)}")

# Agregación por eje
print(f"\nSuma por filas: {np.sum(arr, axis=0)}")
print(f"Suma por columnas: {np.sum(arr, axis=1)}")
print(f"Media por filas: {np.mean(arr, axis=0)}")

# Funciones de agregación avanzadas
print(f"\nMediana: {np.median(arr)}")
print(f"Percentil 75: {np.percentile(arr, 75)}")
print(f"Varianza: {np.var(arr):.2f}")

Array 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Suma total: 45
Media total: 5.00
Desviación estándar total: 2.58
Mínimo: 1
Máximo: 9

Suma por filas: [12 15 18]
Suma por columnas: [ 6 15 24]
Media por filas: [4. 5. 6.]

Mediana: 5.0
Percentil 75: 7.0
Varianza: 6.67


<span style="color:#FFD633; font-weight:bold;">**BUENA PRÁCTICA**:</span> Las funciones de agregación como `sum`, `mean`, `std` son mucho más eficientes en NumPy que sus equivalentes en Python puro.

#### <div style="color:#4DA6FF; text-align:center;">**Funciones lógicas y de comparación**</div>

In [35]:
arr = np.array([True, False, True, False, True])

print("Array booleano:", arr)
print(f"¿Todos son True? {np.all(arr)}")
print(f"¿Alguno es True? {np.any(arr)}")
print(f"¿Cuántos son True? {np.sum(arr)}")

# Ejemplo práctico: análisis de datos
datos = np.array([15, 22, 18, 25, 30, 12, 28, 16, 24, 19])
print(f"\nDatos: {datos}")
print(f"¿Todos los valores son positivos? {np.all(datos > 0)}")
print(f"¿Algún valor es mayor que 30? {np.any(datos > 30)}")
print(f"¿Cuántos valores están entre 15 y 25? {np.sum((datos >= 15) & (datos <= 25))}")

# Funciones de comparación
print(f"Valor máximo: {np.max(datos)}")
print(f"Valor mínimo: {np.min(datos)}")
print(f"Índice del máximo: {np.argmax(datos)}")
print(f"Índice del mínimo: {np.argmin(datos)}")

Array booleano: [ True False  True False  True]
¿Todos son True? False
¿Alguno es True? True
¿Cuántos son True? 3

Datos: [15 22 18 25 30 12 28 16 24 19]
¿Todos los valores son positivos? True
¿Algún valor es mayor que 30? False
¿Cuántos valores están entre 15 y 25? 7
Valor máximo: 30
Valor mínimo: 12
Índice del máximo: 4
Índice del mínimo: 5


## <div style="color:#4DA6FF;">*4.4 Indexación y Slicing Avanzado*</div>

### <div style="color:#4DA6FF;">**Indexación Básica y Slicing**</div>

La indexación en NumPy es similar a la de las listas de Python, pero con capacidades adicionales para arrays multidimensionales.


In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Primer elemento:", arr[0])           # 0
print("Último elemento:", arr[-1])          # 9
print("Elementos del 2 al 6:", arr[2:7])   # [2 3 4 5 6]
print("Elementos de 2 en 2:", arr[::2])    # [0 2 4 6 8]
print("Elementos en orden inverso:", arr[::-1])  # [9 8 7 6 5 4 3 2 1 0]

Primer elemento: 0
Último elemento: 9
Elementos del 2 al 6: [2 3 4 5 6]
Elementos de 2 en 2: [0 2 4 6 8]
Elementos en orden inverso: [9 8 7 6 5 4 3 2 1 0]


### <div style="color:#4DA6FF;">**Indexación en Arrays Multidimensionales**</div>


In [15]:
arr_2d = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])

print("Array 2D:")
print(arr_2d)

print("Primera fila:", arr_2d[0])           # [1 2 3]
print("Elemento en posición (1, 2):", arr_2d[1, 2])  # 6
print("Primeras dos filas:")
print(arr_2d[:2])
print("Últimas dos columnas:")
print(arr_2d[:, 1:])

Array 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Primera fila: [1 2 3]
Elemento en posición (1, 2): 6
Primeras dos filas:
[[1 2 3]
 [4 5 6]]
Últimas dos columnas:
[[2 3]
 [5 6]
 [8 9]]


### <div style="color:#4DA6FF;">**Indexación Booleana: Filtrado Avanzado**</div>

<span style="color:#FFD633; font-weight:bold;">**BUENA PRÁCTICA**:</span> La indexación booleana es una técnica poderosa que permite seleccionar elementos basándose en condiciones lógicas.

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Crear máscara booleana
mask = arr > 5
print("Máscara (elementos > 5):", mask)

# Aplicar la máscara
print("Elementos mayores que 5:", arr[mask])

# Operaciones más complejas
print("Elementos pares:", arr[arr % 2 == 0])
print("Elementos entre 3 y 7:", arr[(arr >= 3) & (arr <= 7)])

# Ejemplo práctico: filtrar datos
temperaturas = np.array([15, 22, 18, 25, 30, 12, 28, 16, 24, 19])
print("Temperaturas altas (>20°C):", temperaturas[temperaturas > 20])

Máscara (elementos > 5): [False False False False False  True  True  True  True  True]
Elementos mayores que 5: [ 6  7  8  9 10]
Elementos pares: [ 2  4  6  8 10]
Elementos entre 3 y 7: [3 4 5 6 7]
Temperaturas altas (>20°C): [22 25 30 28 24]


### <div style="color:#4DA6FF;">**Fancy Indexing**<i style="color:#4DA6FF;"> (Indexación Elegante)</i></div>

In [17]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Indexación con arrays de enteros
indices = [0, 2, 4, 6, 8]
print("Elementos en índices específicos:", arr[indices])

# Indexación con arrays booleanos
indices_bool = np.array([True, False, True, False, True, False, True, False, True, False])
print("Elementos seleccionados:", arr[indices_bool])

# Indexación mixta
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Elementos específicos:", arr_2d[[0, 2], [1, 2]])

Elementos en índices específicos: [10 30 50 70 90]
Elementos seleccionados: [10 30 50 70 90]
Elementos específicos: [2 9]


## <div style="color:#4DA6FF;">*4.5 Manipulación de Arrays: Reshape y Transpose*</div>

### <div style="color:#4DA6FF;">**Cambio de Forma (Reshape)**</div>


NumPy proporciona funciones para cambiar la forma y estructura de los arrays sin modificar los datos subyacentes.

In [18]:
arr = np.arange(12)
print("Array original:", arr)

# Cambiar a 3x4
arr_3x4 = arr.reshape(3, 4)
print("\nReshape a 3x4:")
print(arr_3x4)

# Cambiar a 2x6
arr_2x6 = arr.reshape(2, 6)
print("\nReshape a 2x6:")
print(arr_2x6)

# Usar -1 para inferir automáticamente una dimensión
arr_auto = arr.reshape(3, -1)  # -1 se convierte en 4
print("\nReshape automático:")
print(arr_auto)

# Aplanar arrays
arr_flat = arr_3x4.flatten()
print("\nArray aplanado:", arr_flat)

Array original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshape a 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshape a 2x6:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Reshape automático:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Array aplanado: [ 0  1  2  3  4  5  6  7  8  9 10 11]


### <div style="color:#4DA6FF;">**Transposición y Cambio de Ejes**</div>

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array original:")
print(arr)

print("\nTranspuesto:")
print(arr.T)

# Cambiar ejes
arr_3d = np.arange(24).reshape(2, 3, 4)
print("\nArray 3D:")
print(arr_3d)

print("\nTranspuesto (0, 2, 1):")
print(arr_3d.transpose(0, 2, 1))

# Rotar arrays
print("\nRotado 90 grados:")
print(np.rot90(arr))

Array original:
[[1 2 3]
 [4 5 6]]

Transpuesto:
[[1 4]
 [2 5]
 [3 6]]

Array 3D:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Transpuesto (0, 2, 1):
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]

Rotado 90 grados:
[[3 6]
 [2 5]
 [1 4]]


### <div style="color:#4DA6FF;">**Concatenación y División**</div>

In [20]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenar horizontalmente
print("Concatenación horizontal:")
print(np.concatenate([arr1, arr2]))

# Concatenar verticalmente (necesita reshape)
arr1_2d = arr1.reshape(1, -1)
arr2_2d = arr2.reshape(1, -1)
print("\nConcatenación vertical:")
print(np.concatenate([arr1_2d, arr2_2d], axis=0))

# Usar vstack y hstack
print("\nCon vstack:")
print(np.vstack([arr1, arr2]))
print("\nCon hstack:")
print(np.hstack([arr1, arr2]))

# Dividir arrays
arr_large = np.array([1, 2, 3, 4, 5, 6])
print("\nDividido en 3 partes:")
print(np.split(arr_large, 3))

Concatenación horizontal:
[1 2 3 4 5 6]

Concatenación vertical:
[[1 2 3]
 [4 5 6]]

Con vstack:
[[1 2 3]
 [4 5 6]]

Con hstack:
[1 2 3 4 5 6]

Dividido en 3 partes:
[array([1, 2]), array([3, 4]), array([5, 6])]



## <div style="color:#4DA6FF;">*4.6 Generación de Datos Aleatorios*</div>

### <div style="color:#4DA6FF;">**Generación Básica**</div>


NumPy incluye un generador de números aleatorios robusto que es esencial para simulaciones y análisis estadístico.

In [21]:
# Generar un array de 5 números aleatorios entre 0 y 1
random_uniform = np.random.random(5)
print("Números aleatorios uniformes (0-1):", random_uniform)

# Generar 5 enteros aleatorios entre 1 y 100
random_ints = np.random.randint(1, 101, size=5)
print("Enteros aleatorios (1-100):", random_ints)

# Generar 5 números de una distribución normal
random_normal = np.random.normal(0, 1, 5)
print("Números de distribución normal (μ=0, σ=1):", random_normal)

# Generar números de una distribución uniforme discreta
random_choice = np.random.choice([1, 2, 3, 4, 5], size=10)
print("Elecciones aleatorias:", random_choice)

Números aleatorios uniformes (0-1): [0.247354   0.70804351 0.66819702 0.22506231 0.37718313]
Enteros aleatorios (1-100): [82 74 47 31 45]
Números de distribución normal (μ=0, σ=1): [-0.36766055 -0.76923831 -0.40109536  0.58126455 -0.32516641]
Elecciones aleatorias: [3 4 1 3 5 1 2 2 2 3]



### <div style="color:#4DA6FF;">**Arrays con Forma Específica**</div>

In [22]:
# Matriz 3x3 de números aleatorios
random_matrix = np.random.random((3, 3))
print("Matriz 3x3 de números aleatorios:")
print(random_matrix)

# Array de 2x2x2 de números normales
random_3d = np.random.normal(0, 1, (2, 2, 2))
print("\nArray 3D de números normales:")
print(random_3d)

# Generar datos con semilla para reproducibilidad
np.random.seed(42)
reproducible = np.random.random(5)
print("\nNúmeros reproducibles (seed=42):", reproducible)

Matriz 3x3 de números aleatorios:
[[0.47628425 0.8334253  0.11829635]
 [0.54444316 0.84077176 0.31667214]
 [0.15154991 0.07372866 0.60423889]]

Array 3D de números normales:
[[[-0.25964777  2.22577355]
  [-0.03032125 -0.27657283]]

 [[ 1.42876329  0.80499643]
  [-1.97020073 -0.52101567]]]

Números reproducibles (seed=42): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]



### <div style="color:#4DA6FF;">**Distribuciones Estadísticas**</div>

In [23]:
# Distribución normal
normal_data = np.random.normal(100, 15, 1000)  # μ=100, σ=15, 1000 muestras

# Distribución exponencial
exponential_data = np.random.exponential(2, 1000)  # λ=2, 1000 muestras

# Distribución binomial
binomial_data = np.random.binomial(10, 0.5, 1000)  # n=10, p=0.5, 1000 ensayos

print(f"Normal - Media: {np.mean(normal_data):.2f}, Desv. Est: {np.std(normal_data):.2f}")
print(f"Exponencial - Media: {np.mean(exponential_data):.2f}")
print(f"Binomial - Media: {np.mean(binomial_data):.2f}")

# Generador moderno (recomendado)
rng = np.random.default_rng(seed=42)
modern_normal = rng.normal(0, 1, 1000)
print(f"Generador moderno - Media: {np.mean(modern_normal):.2f}")

Normal - Media: 100.38, Desv. Est: 15.01
Exponencial - Media: 2.01
Binomial - Media: 4.97
Generador moderno - Media: -0.03



## <div style="color:#4DA6FF;">*4.7 Álgebra Lineal con NumPy*</div>

### <div style="color:#4DA6FF;">**Operaciones Básicas con Matrices**</div>
NumPy proporciona funciones básicas para operaciones de álgebra lineal.

In [24]:
# Matrices de ejemplo
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)

# Multiplicación de matrices
print("\nMultiplicación de matrices (A × B):")
print(np.dot(A, B))

# También se puede usar el operador @
print("\nUsando operador @:")
print(A @ B)

# Multiplicación elemento a elemento (Hadamard)
print("\nMultiplicación elemento a elemento:")
print(A * B)

Matriz A:
[[1 2]
 [3 4]]

Matriz B:
[[5 6]
 [7 8]]

Multiplicación de matrices (A × B):
[[19 22]
 [43 50]]

Usando operador @:
[[19 22]
 [43 50]]

Multiplicación elemento a elemento:
[[ 5 12]
 [21 32]]



### <div style="color:#4DA6FF;">**Determinante y Valores Propios**</div>

In [25]:
# Calcular determinante
det_A = np.linalg.det(A)
print(f"Determinante de A: {det_A}")

# Calcular valores propios
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"\nValores propios de A: {eigenvalues}")
print("Vectores propios de A:")
print(eigenvectors)

# Verificar que A*v = λ*v
for i, (eigenvalue, eigenvector) in enumerate(zip(eigenvalues, eigenvectors.T)):
    result = A @ eigenvector
    expected = eigenvalue * eigenvector
    print(f"\nValor propio {i+1}: λ = {eigenvalue:.4f}")
    print(f"A*v = {result}")
    print(f"λ*v = {expected}")

Determinante de A: -2.0000000000000004

Valores propios de A: [-0.37228132  5.37228132]
Vectores propios de A:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Valor propio 1: λ = -0.3723
A*v = [ 0.30697009 -0.21062466]
λ*v = [ 0.30697009 -0.21062466]

Valor propio 2: λ = 5.3723
A*v = [-2.23472698 -4.88542751]
λ*v = [-2.23472698 -4.88542751]



### <div style="color:#4DA6FF;">**Sistemas de Ecuaciones Lineales**</div>

In [26]:
# Sistema Ax = b
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 6])

print("Sistema de ecuaciones:")
print("2x + y = 5")
print("x + 3y = 6")

# Resolver usando np.linalg.solve
x = np.linalg.solve(A, b)
print(f"\nSolución: x = {x[0]:.2f}, y = {x[1]:.2f}")

# Verificar la solución
verification = A @ x
print(f"Verificación: A*x = {verification}")
print(f"Valor esperado: b = {b}")

Sistema de ecuaciones:
2x + y = 5
x + 3y = 6

Solución: x = 1.80, y = 1.40
Verificación: A*x = [5. 6.]
Valor esperado: b = [5 6]



### <div style="color:#4DA6FF;">**Funciones de Álgebra Lineal Comunes**</div>

In [27]:
# Matriz identidad
I = np.eye(3)
print("Matriz identidad 3x3:")
print(I)

# Matriz inversa
A_inv = np.linalg.inv(A)
print(f"\nInversa de A:")
print(A_inv)

# Verificar A * A^(-1) = I
identity_check = A @ A_inv
print(f"\nVerificación A * A^(-1):")
print(identity_check)

# Rango de una matriz
rank_A = np.linalg.matrix_rank(A)
print(f"\nRango de A: {rank_A}")

# Descomposición QR
Q, R = np.linalg.qr(A)
print(f"\nDescomposición QR:")
print("Q:")
print(Q)
print("R:")
print(R)

Matriz identidad 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Inversa de A:
[[ 0.6 -0.2]
 [-0.2  0.4]]

Verificación A * A^(-1):
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]

Rango de A: 2

Descomposición QR:
Q:
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
R:
[[-2.23606798 -2.23606798]
 [ 0.          2.23606798]]



## <div style="color:#4DA6FF;">*4.8 Resumen de Buenas Prácticas de NumPy*</div>

### <div style="color:#4DA6FF;">**1. Evitar Copias Innecesarias**</div>

<span style="color:#FFD633; font-weight:bold;">**BUENA PRÁCTICA**:</span> Usar vistas (views) en lugar de copias cuando sea posible para ahorrar memoria.


In [28]:
arr = np.array([1, 2, 3, 4, 5])

# Vista (no copia) - modifica el array original
view = arr[1:4]
view[0] = 99
print("Array original modificado por la vista:")
print(arr)

# Copia explícita - no modifica el array original
copy = arr[1:4].copy()
copy[0] = 88
print("\nArray original no modificado por la copia:")
print(arr)

Array original modificado por la vista:
[ 1 99  3  4  5]

Array original no modificado por la copia:
[ 1 99  3  4  5]



### <div style="color:#4DA6FF;">**2. Uso Eficiente de la Memoria**</div>

In [29]:
# Comparar uso de memoria
arr_int32 = np.array([1, 2, 3, 4], dtype=np.int32)
arr_int64 = np.array([1, 2, 3, 4], dtype=np.int64)

print(f"Tamaño en bytes - int32: {arr_int32.nbytes}")
print(f"Tamaño en bytes - int64: {arr_int64.nbytes}")
print(f"Factor de ahorro: {arr_int64.nbytes / arr_int32.nbytes:.1f}x")

# Para arrays grandes, la diferencia es significativa
large_arr_int32 = np.zeros(1000000, dtype=np.int32)
large_arr_int64 = np.zeros(1000000, dtype=np.int64)

print(f"\nArray grande int32: {large_arr_int32.nbytes / 1024 / 1024:.1f} MB")
print(f"Array grande int64: {large_arr_int64.nbytes / 1024 / 1024:.1f} MB")

Tamaño en bytes - int32: 16
Tamaño en bytes - int64: 32
Factor de ahorro: 2.0x

Array grande int32: 3.8 MB
Array grande int64: 7.6 MB



### <div style="color:#4DA6FF;">**3. Vectorización en Lugar de Bucles**</div>

<span style="color:#FFD633; font-weight:bold;">**BUENA PRÁCTICA**:</span>La vectorización es la clave del rendimiento en NumPy.

In [30]:
# ❌ Forma ineficiente (con bucle)
def slow_square(arr):
    result = np.zeros_like(arr)
    for i in range(len(arr)):
        result[i] = arr[i] ** 2
    return result

# ✅ Forma eficiente (vectorizada)
def fast_square(arr):
    return arr ** 2

# Comparar rendimiento
large_arr = np.random.random(1000000)

print("Comparando rendimiento:")
print("Con bucle:")
%timeit slow_square(large_arr)

print("\nVectorizado:")
%timeit fast_square(large_arr)

Comparando rendimiento:
Con bucle:
123 ms ± 2.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Vectorizado:
3.29 ms ± 450 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
